credentials:
    auth_type: Client
    client_id_sops: ENC[AES256_GCM,data:w+QlOJj6HMkY8LXI+rhkU+WGzrC/pz70nnZMpqrYbLcLBBnd4MAvPOJrY9GCa1CazfzavL6ATXZtMO2et7IT8PH5i4OkhHmXrcRpYvoQFYqVPOsXMw==,iv:lto0AF8YNlhb9FIntaqVRcyxaEZSxhefzCcDx/2yQFw=,tag:BAIe1Yezo1mnaxz/uPfbaQ==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:MTa+Cv+YH7v8gy/LTsviFW9oocCDWp86g7aB5OVnO6OJLPChbNAuC7qtAzNKiZu2DVKof9tmrjqQcWxhdVEMJA==,iv:oZg6cFFx9Oq3AZCGsGRtusXEZKyMVMKbG6SCANxjwWg=,tag:iyHdLX2mUFKQfo3oJRCneg==,type:str]
    refresh_token_sops: ENC[AES256_GCM,data:/TaTSN6bLz+eZxZhWPYj3ESFZrjQa7XWbzosSNc64Y3Y320n2il9OW2PUzt03rA4FcciEeFAN5IZAm3G+0VnO6ORFo4Bb2OuO7ZkEq9W1NlCen6ulRmb,iv:iWxXdwyum8STeLupLNiFDMcqOsCe/0LUMp6sUkydXHU=,tag:w4n604HbGtpo2JjbUPbIUg==,type:str]
is_sandbox: false
start_date: "2020-01-01"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-03-08T05:31:16Z"
          enc: CiQAdmEdwvWWci8hmYfDEI3t5/hMDMNae/7Pq6THGr3n3y+b8CwSSQCVvC1zN8IPDTYZdbVo11k7xVAeJSNRRAIOPpU+ARe73YpQtoMP92xJs0VasYa6gxjB53wWKIHiGxYJr5rYtJfvE6evYRQFkDY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-11T10:03:34Z"
    mac: ENC[AES256_GCM,data:hbOhtVqgpp3Qjb2J5v0O16tZR7OOaRXhrx989jOWaPg/GRnmT2Wy7DIcT0OKtIR/Xz39xW7AUqYbig6uleMKMpqPKawvd6sPhox+0FfOZzcJDiNsn6P//mJ0/armwS9KnZk+tybhTjJMzHtaI4llp9IBdWJvLncvtZ2PLhA3oqE=,iv:nexmF7WR7PlN9aPVsx+VybCpfE6OY/yWaIPY/0wmbnU=,tag:3Oc35qCorGulnYggINzdPQ==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
