[tool.poetry]
name = "source-salesforce"
version = "0.1.0"
description = ""
authors = ["Luishfs <luish1980@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
airbyte-cdk = ">=0.2,<1.0"
pandas = "^2.2.1"
vcrpy = "4.1.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-insta = "^0.2.0"
mock = "^5.1.0"
pytest-mock = "^3.12.0"
requests-mock = "^1.11.0"
debugpy = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
