---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  AuthOptionsAuthProvider:
    type:
      - boolean
      - "null"
  AuthOptionsCertificate:
    type:
      - boolean
      - "null"
  AuthOptionsSaml:
    type:
      - boolean
      - "null"
  AuthOptionsUsernamePassword:
    type:
      - boolean
      - "null"
  CreatedById:
    type:
      - string
      - "null"
  CreatedDate:
    format: date-time
    type:
      - string
      - "null"
  DeveloperName:
    type:
      - string
      - "null"
  Id:
    type: string
  IsActive:
    type:
      - boolean
      - "null"
  IsDeleted:
    type:
      - boolean
      - "null"
  Language:
    type:
      - string
      - "null"
  LastModifiedById:
    type:
      - string
      - "null"
  LastModifiedDate:
    format: date-time
    type:
      - string
      - "null"
  MasterLabel:
    type:
      - string
      - "null"
  NamespacePrefix:
    type:
      - string
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
  Type:
    type:
      - string
      - "null"
  Url:
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
