---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  CreatedById:
    type:
      - string
      - "null"
  CreatedDate:
    format: date-time
    type:
      - string
      - "null"
  Id:
    type: string
  LastModifiedById:
    type:
      - string
      - "null"
  LastModifiedDate:
    format: date-time
    type:
      - string
      - "null"
  MobileSessionTimeout:
    type:
      - string
      - "null"
  MobileStartUrl:
    type:
      - string
      - "null"
  Name:
    type:
      - string
      - "null"
  OptionsAllowAdminApprovedUsersOnly:
    type:
      - boolean
      - "null"
  OptionsFullContentPushNotifications:
    type:
      - boolean
      - "null"
  OptionsHasSessionLevelPolicy:
    type:
      - boolean
      - "null"
  OptionsIsInternal:
    type:
      - boolean
      - "null"
  OptionsRefreshTokenValidityMetric:
    type:
      - boolean
      - "null"
  PinLength:
    type:
      - string
      - "null"
  RefreshTokenValidityPeriod:
    type:
      - integer
      - "null"
  StartUrl:
    type:
      - string
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
