---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  Amount:
    type:
      - number
      - "null"
  AppliedDate:
    format: date-time
    type:
      - string
      - "null"
  CreatedById:
    type:
      - string
      - "null"
  CreatedDate:
    format: date-time
    type:
      - string
      - "null"
  CreditMemoId:
    type:
      - string
      - "null"
  CreditMemoInvoiceNumber:
    type:
      - string
      - "null"
  Date:
    format: date-time
    type:
      - string
      - "null"
  Description:
    type:
      - string
      - "null"
  EffectiveDate:
    format: date-time
    type:
      - string
      - "null"
  Id:
    type: string
  InvoiceId:
    type:
      - string
      - "null"
  IsDeleted:
    type:
      - boolean
      - "null"
  LastModifiedById:
    type:
      - string
      - "null"
  LastModifiedDate:
    format: date-time
    type:
      - string
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
  Type:
    type:
      - string
      - "null"
  UnappliedDate:
    format: date-time
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
