---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  Description:
    type:
      - string
      - "null"
  EndDate:
    format: date-time
    type:
      - string
      - "null"
  Id:
    type: string
  IsStandardYear:
    type:
      - boolean
      - "null"
  Name:
    type:
      - string
      - "null"
  PeriodId:
    type:
      - string
      - "null"
  PeriodLabelScheme:
    type:
      - string
      - "null"
  PeriodPrefix:
    type:
      - string
      - "null"
  QuarterLabelScheme:
    type:
      - string
      - "null"
  QuarterPrefix:
    type:
      - string
      - "null"
  StartDate:
    format: date-time
    type:
      - string
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
  WeekLabelScheme:
    type:
      - string
      - "null"
  WeekStartDay:
    type:
      - integer
      - "null"
  YearType:
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
