---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  CreatedById:
    type:
      - string
      - "null"
  CreatedDate:
    format: date-time
    type:
      - string
      - "null"
  Id:
    type: string
  IsDeleted:
    type:
      - boolean
      - "null"
  LastModifiedById:
    type:
      - string
      - "null"
  LastModifiedDate:
    format: date-time
    type:
      - string
      - "null"
  Name:
    type:
      - string
      - "null"
  ProductId:
    type:
      - string
      - "null"
  Sequence:
    type:
      - integer
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
  VariantParentId:
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
