---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  CreatedById:
    type:
      - string
      - "null"
  CreatedDate:
    format: date-time
    type:
      - string
      - "null"
  Description:
    type:
      - string
      - "null"
  DisplayUrl:
    type:
      - string
      - "null"
  ExternalDataSourceId:
    type:
      - string
      - "null"
  ExternalId:
    type:
      - string
      - "null"
  Family:
    type:
      - string
      - "null"
  Id:
    type: string
  IsActive:
    type:
      - boolean
      - "null"
  IsArchived:
    type:
      - boolean
      - "null"
  IsDeleted:
    type:
      - boolean
      - "null"
  LastModifiedById:
    type:
      - string
      - "null"
  LastModifiedDate:
    format: date-time
    type:
      - string
      - "null"
  LastReferencedDate:
    format: date-time
    type:
      - string
      - "null"
  LastViewedDate:
    format: date-time
    type:
      - string
      - "null"
  Name:
    type:
      - string
      - "null"
  ProductClass:
    type:
      - string
      - "null"
  ProductCode:
    type:
      - string
      - "null"
  QuantityUnitOfMeasure:
    type:
      - string
      - "null"
  StockKeepingUnit:
    type:
      - string
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
  Type:
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
