---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  CatalogId:
    type:
      - string
      - "null"
  CreatedById:
    type:
      - string
      - "null"
  CreatedDate:
    format: date-time
    type:
      - string
      - "null"
  Description:
    type:
      - string
      - "null"
  Id:
    type: string
  IsDeleted:
    type:
      - boolean
      - "null"
  IsNavigational:
    type:
      - boolean
      - "null"
  LastModifiedById:
    type:
      - string
      - "null"
  LastModifiedDate:
    format: date-time
    type:
      - string
      - "null"
  LastReferencedDate:
    format: date-time
    type:
      - string
      - "null"
  LastViewedDate:
    format: date-time
    type:
      - string
      - "null"
  Name:
    type:
      - string
      - "null"
  NumberOfProducts:
    type:
      - integer
      - "null"
  ParentCategoryId:
    type:
      - string
      - "null"
  SortOrder:
    type:
      - integer
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
