---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  ApprovalRequired:
    type:
      - string
      - "null"
  ConnectedAppId:
    type:
      - string
      - "null"
  CreatedById:
    type:
      - string
      - "null"
  CreatedDate:
    format: date-time
    type:
      - string
      - "null"
  DeveloperName:
    type:
      - string
      - "null"
  Enabled:
    type:
      - boolean
      - "null"
  EnabledOperations:
    type:
      - string
      - "null"
  Id:
    type: string
  IsDeleted:
    type:
      - boolean
      - "null"
  Language:
    type:
      - string
      - "null"
  LastModifiedById:
    type:
      - string
      - "null"
  LastModifiedDate:
    format: date-time
    type:
      - string
      - "null"
  LastReconDateTime:
    format: date-time
    type:
      - string
      - "null"
  MasterLabel:
    type:
      - string
      - "null"
  NamedCredentialId:
    type:
      - string
      - "null"
  NamespacePrefix:
    type:
      - string
      - "null"
  Notes:
    type:
      - string
      - "null"
  OnUpdateAttributes:
    type:
      - string
      - "null"
  ReconFilter:
    type:
      - string
      - "null"
  SystemModstamp:
    format: date-time
    type:
      - string
      - "null"
  UserAccountMapping:
    type:
      - string
      - "null"
reduce:
  strategy: merge
required:
  - Id
type: object
